apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka_setupper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka_setupper
  template:
    metadata:
      labels:
        app: kafka_setupper
    spec:
      containers:
      - name: kafka_setupper
        ports:
        - containerPort: 81