apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram_bot_reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram_bot_reader
  template:
    metadata:
      labels:
        app: telegram_bot_reader
    spec:
      containers:
      - name: telegram_bot_reader
        ports:
        - containerPort: 89