apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoo1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zoo1
  template:
    metadata:
      labels:
        app: zoo1
    spec:
      containers:
      - name: zoo1
        image: confluentinc/cp-zookeeper:7.3.2
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_SERVER_ID
          value: "1"
        - name: ZOOKEEPER_SERVERS
          value: "zoo1:2888:3888"